<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<title>admin | initWithFrame</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.4/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.4/dist/semantic.min.js"></script>

    <link rel="stylesheet" type="text/css" href="<?= URL ?>public/css/site.css">
</head>
<body>
    <?php if (isset($_SESSION['loginValid']) && $_SESSION['loginValid'] === true) { ?>
        <div class="ui inverted fixed vertical labeled menu" id="mainMenu">
            <div class="purpleText header item">initWithFrame</div>
            <a href="<?= URL ?>packages/index" class="item"><i class="box icon"></i> Packages</a>
            <a href="<?= URL ?>packages/index" class="item"><i class="settings icon"></i> Settings</a>
            <div class="bottomMenu">
                <a href="<?= URL ?>user/logout" class="item"><i class="sign out icon"></i> Logout</a>
            </div>
        </div>
    <?php } ?>

    <div class="ui container">
